<h1 style="text-align: center; font-family: 'JetBrains Mono'; color: purple;"><b>CHAPTER 3: REPORT</b></h1>

https://pypi.org/project/tabulate/ <br>
https://pypi.org/project/python-csv/

In [1]:
#LIBRARY 

import csv
from tabulate import tabulate

MINIMUM_CREDIT = 15  # condition

# Input file and print input table


#INPUT GUI FUNCTION
def input_table():
    list_candidate = []
    with open("C:/Local Code/Projects/PyCharmProject/Chapter3Project/stack.csv", "r", encoding="UTF-8") as input_file:
        candidate = csv.DictReader(input_file)
        for line in candidate:
            list_candidate.append(line)
    
    print(tabulate(
        list_candidate,
        headers=["Student Name", "Overall GPA", "Letter Grade", "Total Credits","Scholar"],
        tablefmt="fancy_grid"
    ))


#SUBFUNCTION

def calculate_average(list_courses):
    if not list_courses:  # Check if the list is empty
        return 0
    total_average = sum(list_courses) / len(list_courses)
    return total_average

def stack_average(values):
    if values > 8.5:
        return "A+"
    elif 8 <= values <= 8.5:
        return "A"
    elif 7 <= values < 8:
        return "B+"
    elif 6 <= values < 7:
        return "B"
    elif 5 <= values < 6:
        return "C"
    else:
        return "F, Fail"

def stack_scholar(total_average, student_credits): #condition function
    # Check if student qualifies for a scholarship
    if total_average >= 8 and student_credits >= MINIMUM_CREDIT:
        return True
    else:
        return False


#OUTPUT
def output_table(final_results):
    with open("C:/Local Code/Projects/PyCharmProject/Chapter3Project/output_stack.csv", "w", encoding="UTF-8", newline='') as output_file:
        writer = csv.writer(output_file)
        writer.writerow(["Student Name", "Overall GPA", "Letter Grade", "Total Credits", "Scholar"])
        for student_name, overall_gpa, letter_grade, total_credits, scholar_status in final_results:
            writer.writerow([student_name, f"{overall_gpa:.2f}", letter_grade, total_credits, scholar_status])



# Main Function
def main():  
    # CSV INPUT
    print("--------------------------------------------------")
    print("SAMPLE TABLE")
    
    input_table() 

    students_averages = []
    student_gpas = {}
    student_credits = {}
    
    print("--------------------------------------------------")
    print("WELCOME TO GPA COUNTING AND ANALYSIS PROGRAM")
    print("--------------------------------------------------")
    print("""
            Select your choice of average point
            1. Average Grade Manually Input
            2. Average Grade Existed
            """)
    print("--------------------------------------------------")
    select = input("Enter your choice (1 or 2): ")
    
    # Setup constraint of course and student execution
    num_courses = int(input("Enter the number of courses: "))
    num_students = int(input("Enter the number of students: "))

    for i in range(num_courses):
        course_name = input(f"\nEnter the name of course {i + 1}: ")
        course_credit = float(input(f"Enter the credit for {course_name}: "))
        for j in range(num_students):
            student_name = input(f"Enter name of Student {j + 1}: ")

            if select == "1":
                process = float(input("Input Process Grade: "))
                mid_term = float(input("Input Midterm Grade: "))
                end_term = float(input("Input Endterm Grade: "))
                course_average = (20/100) * process + (30/100) * mid_term + (50/100) * end_term
            elif select == "2":
                course_average = float(input(f"Enter the GPA for {course_name} for {student_name}: "))
            else:
                print("Invalid choice. Skipping input for this student.")
                continue  # Skip to the next student if the input is invalid
            
            # Calculate letter grade and append data for CSV output
            letter_grade = stack_average(course_average)
            # Ensure that each entry in students_averages has complete data before adding to final_results.
            students_averages.append((student_name, course_average, letter_grade, student_credits[student_name], scholar_status))

            if student_name not in student_gpas:
                student_gpas[student_name] = []
                student_credits[student_name] = 0
            student_gpas[student_name].append(course_average)
            student_credits[student_name] += course_credit

    # Prepare final results
  # Prepare final results
final_results = []
for student_name, averages in student_gpas.items():
    total_average = calculate_average(averages)
    overall_letter_grade = stack_average(total_average)
    scholar_status = stack_scholar(total_average, student_credits[student_name])  # Determine scholar status

    # Format GPA to two decimal places for consistency
    final_results.append(
        [student_name, round(total_average, 2), overall_letter_grade, student_credits[student_name], scholar_status])

# Final output
print("\nFinal GPA Results:\n")
print(tabulate(final_results, headers=["Student Name", "Overall GPA", "Letter Grade", "Total Credits", "Scholar"],
               tablefmt="fancy_grid"))

# CSV Output
output_table(final_results)

if __name__ == "__main__":  # Execute Function
    main()

--------------------------------------------------
SAMPLE TABLE
╒════════════════╤═══════════════╤════════════════╤═════════════════╕
│ Student Name   │ Overall GPA   │ Letter Grade   │ Total Credits   │
╞════════════════╪═══════════════╪════════════════╪═════════════════╡
╘════════════════╧═══════════════╧════════════════╧═════════════════╛
--------------------------------------------------
WELCOME TO GPA COUNTING AND ANALYSIS PROGRAM
--------------------------------------------------

            Select your choice of average point
            1. Average Grade Manually Input
            2. Average Grade Existed

--------------------------------------------------

Enter your choice (1 or 2):  2
Enter the number of courses:  5
Enter the number of students:  6

Enter the name of course 1:  Basic Programming
Enter the credit for Basic Programming:  2
Enter name for Student 1:  Huỳnh Tấn Phát
Enter the average for Basic Programming for Huỳnh Tấn Phát:  9.2
Enter name for Student 2:  Trương Ngọc Thịnh
Enter the average for Basic Programming for Trương Ngọc Thịnh:  9.0
Enter name for Student 3:  Phan Thành Tài
Enter the average for Basic Programming for Phan Thành Tài:  8.2
Enter name for Student 4:  Nguyễn Hoàng Quân
Enter the average for Basic Programming for Nguyễn Hoàng Quân:  7.2
Enter name for Student 5:  Huỳnh Anh Khoa
Enter the average for Basic Programming for Huỳnh Anh Khoa:  7.1
Enter name for Student 6:  Phan Nguyễn Trí Tín
Enter the average for Basic Programming for Phan Nguyễn Trí Tín:  8.0

Enter the name of course 2:  Data Analyst
Enter the credit for Data Analyst:  3
Enter name for Student 1:  Huỳnh Tấn Phát
Enter the average for Data Analyst for Huỳnh Tấn Phát:  7.1
Enter name for Student 2:  Trương Ngọc Thịnh
Enter the average for Data Analyst for Trương Ngọc Thịnh:  9.2
Enter name for Student 3:  Phan Thành Tài
Enter the average for Data Analyst for Phan Thành Tài:  6.1
Enter name for Student 4:  Nguyễn Hoàng Quân
Enter the average for Data Analyst for Nguyễn Hoàng Quân:  7.2
Enter name for Student 5:  Huỳnh Anh Khoa
Enter the average for Data Analyst for Huỳnh Anh Khoa:  4.1
Enter name for Student 6:  Phan Nguyễn Trí Tín
Enter the average for Data Analyst for Phan Nguyễn Trí Tín:  5.2

Enter the name of course 3:  Discrete Data Crawling
Enter the credit for Discrete Data Crawling:  3
Enter name for Student 1:  Huỳnh Tấn Phát
Enter the average for Discrete Data Crawling for Huỳnh Tấn Phát:  4.1
Enter name for Student 2:  Trương Ngọc Thịnh
Enter the average for Discrete Data Crawling for Trương Ngọc Thịnh:  6.4
Enter name for Student 3:  Phan Thành Tài
Enter the average for Discrete Data Crawling for Phan Thành Tài:  9.2
Enter name for Student 4:  Nguyễn Hoàng Quân
Enter the average for Discrete Data Crawling for Nguyễn Hoàng Quân:  6.7
Enter name for Student 5:  Huỳnh Anh Khoa
Enter the average for Discrete Data Crawling for Huỳnh Anh Khoa:  6.4
Enter name for Student 6:  Phan Nguyễn Trí Tín
Enter the average for Discrete Data Crawling for Phan Nguyễn Trí Tín:  7.2

Enter the name of course 4:  International Trade
Enter the credit for International Trade:  3
Enter name for Student 1:  Huỳnh Tấn Phát
Enter the average for International Trade for Huỳnh Tấn Phát:  7.2
Enter name for Student 2:  Trương Ngọc Thịnh
Enter the average for International Trade for Trương Ngọc Thịnh:  8.3
Enter name for Student 3:  Phan Thành Tài
Enter the average for International Trade for Phan Thành Tài:  9.6
Enter name for Student 4:  Nguyễn Hoàng Quân
Enter the average for International Trade for Nguyễn Hoàng Quân:  6.6
Enter name for Student 5:  Huỳnh Anh Khoa
Enter the average for International Trade for Huỳnh Anh Khoa:  8.4
Enter name for Student 6:  Phan Nguyễn Trí Tín
Enter the average for International Trade for Phan Nguyễn Trí Tín:  4.0

Enter the name of course 5:  Econometrics
Enter the credit for Econometrics:  3
Enter name for Student 1:  4
Enter the average for Econometrics for 4:  9.0
Enter name for Student 2:  Trương Ngọc Thịnh
Enter the average for Econometrics for Trương Ngọc Thịnh:  8.2
Enter name for Student 3:  Phan Thành Tài
Enter the average for Econometrics for Phan Thành Tài:  8.3
Enter name for Student 4:  Nguyễn Hoàng Quân
Enter the average for Econometrics for Nguyễn Hoàng Quân:  4.2
Enter name for Student 5:  Huỳnh Anh Khoa
Enter the average for Econometrics for Huỳnh Anh Khoa:  8.2
Enter name for Student 6:  Phan Nguyễn Trí Tín
Enter the average for Econometrics for Phan Nguyễn Trí Tín:  6.6

Final GPA Results:

╒═════════════════════╤═══════════════╤════════════════╤═════════════════╤═══════════╕
│ Student Name        │   Overall GPA │ Letter Grade   │   Total Credits │ Scholar   │
╞═════════════════════╪═══════════════╪════════════════╪═════════════════╪═══════════╡
│ Huỳnh Tấn Phát      │          6.9  │ B              │              11 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ Trương Ngọc Thịnh   │          8.22 │ A              │              14 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ Phan Thành Tài      │          8.28 │ A              │              14 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ Nguyễn Hoàng Quân   │          6.38 │ B              │              14 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ Huỳnh Anh Khoa      │          6.84 │ B              │              14 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ Phan Nguyễn Trí Tín │          6.2  │ B              │              14 │ False     │
├─────────────────────┼───────────────┼────────────────┼─────────────────┼───────────┤
│ 4                   │          9    │ A+             │               3 │ False     │
╘═════════════════════╧═══════════════╧════════════════╧═════════════════╧═══════════╛

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Local Code/Projects/PyCharmProject/Chapter3Project/output_stack.csv")
df

          Student Name  Course Name Average  Letter Grade  Scholar
0       Huỳnh Tấn Phát         6.90       B          11.0    False
1    Trương Ngọc Thịnh         8.22       A          14.0    False
2       Phan Thành Tài         8.28       A          14.0    False
3    Nguyễn Hoàng Quân         6.38       B          14.0    False
4       Huỳnh Anh Khoa         6.84       B          14.0    False
5  Phan Nguyễn Trí Tín         6.20       B          14.0    False
6                    4         9.00      A+           3.0    False

In [11]:
df.columns

Index(['Student Name', 'Course Name', 'Average', 'Letter Grade', 'Scholar'], dtype='object')

In [21]:
import matplotlib.pyplot as plt

# Assuming df is your DataFrame
df.loc[df["Student Name"] == "Huỳnh Tấn Phát"].plot(kind="bar", x="Course Name", y="Average")
plt.show()

TypeError: no numeric data to plot